name: Sync
on:
  push:
    branches:
      - main

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Sync Branches Enhanced
        id: branch-sync
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.LOCAL_TOKEN }}
          FROM_BRANCH: "main"
          TO_BRANCH: "develop"
